In [1]:
import torch

In [2]:
file_path='model'
loaded_model=torch.load(file_path,map_location=torch.device('cpu'))

In [3]:
loaded_model.eval()

MobileNetV2(
  (features): Sequential(
    (0): Conv2dNormActivation(
      (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU6(inplace=True)
    )
    (1): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
          (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (2): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(16, 96, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(96, eps=

In [4]:
for param in loaded_model.parameters():
    print(param)

Parameter containing:
tensor([[[[ 1.3185e-02, -4.3213e-03,  1.4823e-02],
          [ 3.2781e-02, -2.5385e-02,  6.8572e-03],
          [ 1.0549e-02, -3.7347e-02, -1.4727e-02]],

         [[ 7.9917e-03, -5.9146e-03,  1.5076e-02],
          [ 1.9999e-02, -3.2863e-02, -2.0859e-03],
          [ 1.1350e-02, -3.2956e-02, -7.8733e-03]],

         [[-2.5234e-02, -2.0167e-02, -9.9620e-03],
          [-1.1213e-02, -2.9266e-02, -1.5218e-02],
          [-2.6531e-02, -3.3449e-02, -2.4215e-02]]],


        [[[-5.8002e-02, -1.5499e-02,  2.7349e-02],
          [ 1.3127e-01,  3.8066e-01,  4.2788e-02],
          [-1.8684e-01, -2.7832e-01, -3.7542e-02]],

         [[-6.1517e-02,  5.9048e-02,  7.8318e-03],
          [ 2.6741e-01,  7.4954e-01,  1.0240e-01],
          [-3.3554e-01, -6.0770e-01, -7.6095e-02]],

         [[-9.8979e-03, -4.8626e-03,  3.2428e-02],
          [ 4.2921e-02,  1.7415e-01,  2.4361e-03],
          [-6.1280e-02, -1.5576e-01,  1.7342e-03]]],


        [[[-1.0507e-01,  9.7694e-02, -7.6681

In [3]:
import cv2
import numpy as np

In [4]:
#sample predcition
sample_test=cv2.imread('/Users/abhishek/Desktop/PYTHON/Face Mask detection/customtests/685BE1AE-0BDB-4A78-832C-0A6D68D934E8_1_105_c.jpeg')
input_image_resized = cv2.resize(sample_test,(224,224))
input_image_scaled = input_image_resized/255.0
input_image_reshaped = np.reshape(input_image_scaled, (1,3,224,224))
#np to tensor
input_tensor = torch.tensor(input_image_reshaped, dtype=torch.float32)
score = loaded_model(input_tensor)
_,prediction=score.max(1)
print(prediction)


tensor([1])


[W NNPACK.cpp:64] Could not initialize NNPACK! Reason: Unsupported hardware.


In [5]:
#prediction
input_image_path = input('Path of the image to be predicted: ')

input_image = cv2.imread(input_image_path)

input_image_resized = cv2.resize(input_image,(224,224))
input_image_scaled = input_image_resized/255.0
input_image_reshaped = np.reshape(input_image_scaled, (1,3,224,224))
input_tensor = torch.tensor(input_image_reshaped, dtype=torch.float32)
score = loaded_model(input_tensor)

_,input_pred_label = score.max(1)
print(input_pred_label)
if input_pred_label == 1:

  print('The person in the image is wearing a mask')

else:

  print('The person in the image is not wearing a mask')

tensor([1])
The person in the image is wearing a mask


In [6]:
#prediction
input_image_path = input('Path of the image to be predicted: ')

input_image = cv2.imread(input_image_path)

input_image_resized = cv2.resize(input_image,(224,224))
input_image_scaled = input_image_resized/255.0
input_image_reshaped = np.reshape(input_image_scaled, (1,3,224,224))
input_tensor = torch.tensor(input_image_reshaped, dtype=torch.float32)
score = loaded_model(input_tensor)

_,input_pred_label = score.max(1)
print(input_pred_label)
if input_pred_label == 1:

  print('The person in the image is wearing a mask')

else:

  print('The person in the image is not wearing a mask')

tensor([1])
The person in the image is wearing a mask


In [4]:
device='cpu'

In [10]:
#prediction
input_image_path = input('Path of the image to be predicted: ')

input_image = cv2.imread(input_image_path)
input_image_resized = cv2.resize(input_image,(224,224))
input_image_scaled = input_image_resized/255.0
input_image_reshaped = np.reshape(input_image_scaled, (1,3,224,224))
input_tensor = torch.tensor(input_image_reshaped,dtype=torch.float32).to(device)
score = loaded_model(input_tensor).to(device)

_,input_pred_label = score.max(1)
print(input_pred_label)
if input_pred_label == 1:

  print('The person in the image is wearing a mask')

else:

  print('The person in the image is not wearing a mask')

tensor([0])
The person in the image is not wearing a mask


In [13]:
#prediction
input_image_path = input('Path of the image to be predicted: ')

input_image = cv2.imread(input_image_path)
input_image_resized = cv2.resize(input_image,(224,224))
input_image_scaled = input_image_resized/255.0
input_image_reshaped = np.reshape(input_image_scaled, (1,3,224,224))
input_tensor = torch.tensor(input_image_reshaped,dtype=torch.float32).to(device)
score = loaded_model(input_tensor).to(device)

_,input_pred_label = score.max(1)
print(input_pred_label)
if input_pred_label == 1:

  print('The person in the image is wearing a mask')

else:

  print('The person in the image is not wearing a mask')

tensor([0])
The person in the image is not wearing a mask


In [5]:
def predict(img):
    input_image_resized = cv2.resize(img,(224,224))
    input_image_scaled = input_image_resized/255.0
    input_image_reshaped = np.reshape(input_image_scaled, (1,3,224,224))
    input_tensor = torch.tensor(input_image_reshaped,dtype=torch.float32).to(device)
    score = loaded_model(input_tensor).to(device)
    _,input_pred_label = score.max(1)
    return input_pred_label



In [6]:
def draw_label(img,text,pos,bg_color):
    text_size=cv2.getTextSize(text,cv2.FONT_HERSHEY_SIMPLEX,1,cv2.FILLED)
    end_x=pos[0]+text_size[0][0]+2
    end_y=pos[1]+text_size[0][1]-2

    cv2.rectangle(img,pos,(end_x,end_y),bg_color,cv2.FILLED)
    cv2.putText(img,text,pos,cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,0),1,cv2.LINE_AA)


In [7]:
cap=cv2.VideoCapture(0)

2024-06-20 22:17:41.107 python[15710:663772] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.


In [8]:
while True:
    ret,frame=cap.read()
    #call detection method
    y_pred=predict(frame)
    if y_pred==0:
        draw_label(frame,"No Mask",(30,30),(0,255,0))
    else:
        draw_label(frame,"Mask",(30,30),(0,0,255))
    cv2.imshow('window',frame)
    if cv2.waitKey(1) & 0xFF==ord('x'):
        break
cv2.destroyAllWindows()

[W NNPACK.cpp:64] Could not initialize NNPACK! Reason: Unsupported hardware.
